//
//  Wetteronline.swift
//  muensterwetter
//
//  Created by Krystof Beuermann on 31.12.16.
//
//

import Foundation
import Vapor
import Fluent
import Kanna

struct Tageswetter : NodeConvertible
{
    var datum: String
    var tiefsttemperatur: String
    var höchsttemperatur: String
    var sonnenscheindauer: String
    var regenwahrscheinlichkeit: String
    var wettercode: String
    var symbol: String
    
    init(datum: String,tiefsttemperatur: String,höchsttemperatur: String,sonnenscheindauer: String,regenwahrscheinlichkeit: String,wettercode: String, symbol: String)
    {
        self.datum = datum
        self.tiefsttemperatur = tiefsttemperatur
        self.höchsttemperatur = höchsttemperatur
        self.sonnenscheindauer = sonnenscheindauer
        self.regenwahrscheinlichkeit = regenwahrscheinlichkeit
        self.wettercode = wettercode
        self.symbol = symbol
    }
    
    
    func makeNode(context: Context) throws -> Node
    {
        let node = try Node(node: ["datum":datum, "tiefsttemperatur":tiefsttemperatur,"höchsttemperatur":höchsttemperatur, "sonnenscheindauer":sonnenscheindauer,"regenwahrscheinlichkeit":regenwahrscheinlichkeit, "wettercode":wettercode,"symbol":symbol ] )
        return node
    }
    
    init(node: Node, in context: Context) throws
    {
    
         let datum = (node["datum"]?.string) ?? ""
         let tiefsttemperatur = (node["tiefsttemperatur"]?.string) ?? ""
         let höchsttemperatur = (node["höchsttemperatur"]?.string) ?? ""
         let sonnenscheindauer = (node["sonnenscheindauer"]?.string) ?? ""
         let regenwahrscheinlichkeit = (node["regenwahrscheinlichkeit"]?.string) ?? ""
        let  wettercode = (node["wettercode"]?.string) ?? ""
        let  symbol = (node["symbol"]?.string) ?? ""

            self.datum = datum
            self.tiefsttemperatur = tiefsttemperatur
            self.höchsttemperatur = höchsttemperatur
            self.sonnenscheindauer = sonnenscheindauer
            self.regenwahrscheinlichkeit = regenwahrscheinlichkeit
            self.wettercode = wettercode
            self.symbol = symbol

        
    }
    
}

final class MeteomediaWetter {
    
        var dict = Dictionary<String, String>()
        var alleTageswetter = Array<Tageswetter>()
    
    
    init?() {
        
        // Load URL into Kanna
        guard let url = URL(string: "http://weatherpro.consumer.meteogroup.com/weatherpro/WeatherServiceFeed.php?format=xml&lid=18220778&mode=free&uuid=E12A0F7B-5C8E-4860-ABA9-F73C17230F63"),
            let doc = XML(url:url, encoding: .utf8)
            else {
                return nil
        }
        
        var dict = Dictionary<String, String>()
        dict.updateValue("Schleierwolken", forKey: "0;-8")
        dict.updateValue("sonnig", forKey: "0;-7")
        dict.updateValue("sonnig, Sturm", forKey: "0;-6")
        dict.updateValue("sonnig", forKey: "0;-5")
        dict.updateValue("sonnig", forKey: "0;-4")
        dict.updateValue("sonnig", forKey: "0;-3")
        dict.updateValue("sonnig", forKey: "0;-2")
        dict.updateValue("sonnig", forKey: "0;-1")
        dict.updateValue("sonnig", forKey: "0;0")
        dict.updateValue("sonnig", forKey: "0;1")
        dict.updateValue("sonnig", forKey: "0;2")
        dict.updateValue("sonnig", forKey: "0;3")
        dict.updateValue("sonnig", forKey: "0;4")
        dict.updateValue("sonnig", forKey: "0;5")
        dict.updateValue("sonnig", forKey: "0;6")
        dict.updateValue("sonnig", forKey: "0;7")
        dict.updateValue("sonnig", forKey: "0;8")
        dict.updateValue("sonnig", forKey: "0;9")
        dict.updateValue("sonnig, dunstig", forKey: "0;10")
        dict.updateValue("sonnig, Bodennebel", forKey: "0;11")
        dict.updateValue("sonnig, Bodennebel", forKey: "0;12")
        dict.updateValue("sonnig, Wetterleuchten", forKey: "0;13")
        dict.updateValue("sonnig", forKey: "0;14")
        dict.updateValue("sonnig", forKey: "0;15")
        dict.updateValue("sonnig", forKey: "0;16")
        dict.updateValue("sonnig", forKey: "0;17")
        dict.updateValue("sonnig, böig", forKey: "0;18")
        dict.updateValue("sonnig", forKey: "0;19")
        dict.updateValue("sonnig", forKey: "0;20")
        dict.updateValue("sonnig", forKey: "0;21")
        dict.updateValue("sonnig", forKey: "0;22")
        dict.updateValue("sonnig", forKey: "0;23")
        dict.updateValue("Glatteisgefahr", forKey: "0;24")
        dict.updateValue("sonnig", forKey: "0;25")
        dict.updateValue("sonnig", forKey: "0;26")
        dict.updateValue("sonnig", forKey: "0;27")
        dict.updateValue("sonnig", forKey: "0;28")
        dict.updateValue("sonnig", forKey: "0;29")
        dict.updateValue("sonnig, Staubsturm", forKey: "0;30")
        dict.updateValue("sonnig, Staubsturm", forKey: "0;31")
        dict.updateValue("sonnig, Staubsturm", forKey: "0;32")
        dict.updateValue("sonnig, Staubsturm", forKey: "0;33")
        dict.updateValue("sonnig, Staubsturm", forKey: "0;34")
        dict.updateValue("sonnig, Staubsturm", forKey: "0;35")
        dict.updateValue("sonnig, Schneefegen", forKey: "0;36")
        dict.updateValue("sonnig, Schneefegen", forKey: "0;37")
        dict.updateValue("sonnig, Schneetreiben", forKey: "0;38")
        dict.updateValue("sonnig, Schneetreiben", forKey: "0;39")
        dict.updateValue("sonnig, Nebel", forKey: "0;40")
        dict.updateValue("sonnig, Nebeltreiben", forKey: "0;41")
        dict.updateValue("sonnig, Nebel", forKey: "0;42")
        dict.updateValue("sonnig, Nebel", forKey: "0;43")
        dict.updateValue("sonnig, Nebel", forKey: "0;44")
        dict.updateValue("sonnig, Nebel", forKey: "0;45")
        dict.updateValue("sonnig, Nebel", forKey: "0;46")
        dict.updateValue("sonnig, Nebel", forKey: "0;47")
        dict.updateValue("sonnig, Eisnebel", forKey: "0;48")
        dict.updateValue("sonnig, Eisnebel", forKey: "0;49")
        dict.updateValue("sonnig", forKey: "0;50")
        dict.updateValue("sonnig", forKey: "0;51")
        dict.updateValue("sonnig", forKey: "0;52")
        dict.updateValue("sonnig", forKey: "0;53")
        dict.updateValue("sonnig", forKey: "0;54")
        dict.updateValue("sonnig", forKey: "0;55")
        dict.updateValue("sonnig", forKey: "0;56")
        dict.updateValue("sonnig", forKey: "0;57")
        dict.updateValue("sonnig", forKey: "0;58")
        dict.updateValue("sonnig", forKey: "0;59")
        dict.updateValue("sonnig", forKey: "0;60")
        dict.updateValue("sonnig", forKey: "0;61")
        dict.updateValue("sonnig", forKey: "0;62")
        dict.updateValue("sonnig", forKey: "0;63")
        dict.updateValue("sonnig", forKey: "0;64")
        dict.updateValue("sonnig", forKey: "0;65")
        dict.updateValue("sonnig", forKey: "0;66")
        dict.updateValue("sonnig", forKey: "0;67")
        dict.updateValue("sonnig", forKey: "0;68")
        dict.updateValue("sonnig", forKey: "0;69")
        dict.updateValue("sonnig", forKey: "0;70")
        dict.updateValue("sonnig", forKey: "0;71")
        dict.updateValue("sonnig", forKey: "0;72")
        dict.updateValue("sonnig", forKey: "0;73")
        dict.updateValue("sonnig", forKey: "0;74")
        dict.updateValue("sonnig", forKey: "0;75")
        dict.updateValue("sonnig", forKey: "0;76")
        dict.updateValue("sonnig", forKey: "0;77")
        dict.updateValue("sonnig", forKey: "0;78")
        dict.updateValue("sonnig", forKey: "0;79")
        dict.updateValue("sonnig", forKey: "0;80")
        dict.updateValue("sonnig", forKey: "0;81")
        dict.updateValue("sonnig", forKey: "0;82")
        dict.updateValue("sonnig", forKey: "0;83")
        dict.updateValue("sonnig", forKey: "0;84")
        dict.updateValue("sonnig", forKey: "0;85")
        dict.updateValue("sonnig", forKey: "0;86")
        dict.updateValue("sonnig", forKey: "0;87")
        dict.updateValue("sonnig", forKey: "0;88")
        dict.updateValue("sonnig", forKey: "0;89")
        dict.updateValue("sonnig", forKey: "0;90")
        dict.updateValue("sonnig", forKey: "0;91")
        dict.updateValue("sonnig", forKey: "0;92")
        dict.updateValue("sonnig", forKey: "0;93")
        dict.updateValue("sonnig", forKey: "0;94")
        dict.updateValue("sonnig", forKey: "0;95")
        dict.updateValue("sonnig", forKey: "0;96")
        dict.updateValue("sonnig", forKey: "0;97")
        dict.updateValue("sonnig", forKey: "0;98")
        dict.updateValue("sonnig", forKey: "0;99")
        dict.updateValue("heiter, Schleierwolken", forKey: "1;-8")
        dict.updateValue("heiter", forKey: "1;-7")
        dict.updateValue("heiter, Sturm", forKey: "1;-6")
        dict.updateValue("heiter", forKey: "1;-5")
        dict.updateValue("heiter", forKey: "1;-4")
        dict.updateValue("heiter", forKey: "1;-3")
        dict.updateValue("heiter", forKey: "1;-2")
        dict.updateValue("heiter", forKey: "1;-1")
        dict.updateValue("heiter", forKey: "1;0")
        dict.updateValue("heiter", forKey: "1;1")
        dict.updateValue("heiter", forKey: "1;2")
        dict.updateValue("heiter", forKey: "1;3")
        dict.updateValue("heiter", forKey: "1;4")
        dict.updateValue("heiter", forKey: "1;5")
        dict.updateValue("heiter", forKey: "1;6")
        dict.updateValue("heiter", forKey: "1;7")
        dict.updateValue("heiter", forKey: "1;8")
        dict.updateValue("heiter", forKey: "1;9")
        dict.updateValue("heiter, dunstig", forKey: "1;10")
        dict.updateValue("heiter, Bodennebel", forKey: "1;11")
        dict.updateValue("heiter, Bodennebel", forKey: "1;12")
        dict.updateValue("heiter, Wetterleuchten", forKey: "1;13")
        dict.updateValue("heiter, Tropfen möglich", forKey: "1;14")
        dict.updateValue("heiter, etwas Regen", forKey: "1;15")
        dict.updateValue("heiter, etwas Regen", forKey: "1;16")
        dict.updateValue("heiter, gewittrig", forKey: "1;17")
        dict.updateValue("heiter, böig", forKey: "1;18")
        dict.updateValue("heiter, Tornado", forKey: "1;19")
        dict.updateValue("heiter, Sprühregen", forKey: "1;20")
        dict.updateValue("heiter, Regen", forKey: "1;21")
        dict.updateValue("heiter, Schneefall", forKey: "1;22")
        dict.updateValue("heiter, Schneeregen", forKey: "1;23")
        dict.updateValue("heiter, Schneeregen mit Glatteisgefahr", forKey: "1;24")
        dict.updateValue("heiter, Regenschauer", forKey: "1;25")
        dict.updateValue("heiter, Schneeschauer", forKey: "1;26")
        dict.updateValue("heiter, Graupelschauer", forKey: "1;27")
        dict.updateValue("heiter, Nebel", forKey: "1;28")
        dict.updateValue("heiter, gewittrig", forKey: "1;29")
        dict.updateValue("heiter, Staubsturm", forKey: "1;30")
        dict.updateValue("heiter, Staubsturm", forKey: "1;31")
        dict.updateValue("heiter, Staubsturm", forKey: "1;32")
        dict.updateValue("heiter, Staubsturm", forKey: "1;33")
        dict.updateValue("heiter, Staubsturm", forKey: "1;34")
        dict.updateValue("heiter, Staubsturm", forKey: "1;35")
        dict.updateValue("heiter, Schneefegen", forKey: "1;36")
        dict.updateValue("heiter, Schneefegen", forKey: "1;37")
        dict.updateValue("heiter, Schneetreiben", forKey: "1;38")
        dict.updateValue("heiter, Schneetreiben", forKey: "1;39")
        dict.updateValue("heiter, Nebel", forKey: "1;40")
        dict.updateValue("heiter, Nebeltreiben", forKey: "1;41")
        dict.updateValue("heiter, Nebel", forKey: "1;42")
        dict.updateValue("heiter, Nebel", forKey: "1;43")
        dict.updateValue("heiter, Nebel", forKey: "1;44")
        dict.updateValue("heiter, Nebel", forKey: "1;45")
        dict.updateValue("heiter, Nebel", forKey: "1;46")
        dict.updateValue("heiter, Nebel", forKey: "1;47")
        dict.updateValue("heiter, Eisnebel", forKey: "1;48")
        dict.updateValue("heiter, Eisnebel", forKey: "1;49")
        dict.updateValue("heiter, leichter Sprühregen", forKey: "1;50")
        dict.updateValue("heiter, leichter Sprühregen", forKey: "1;51")
        dict.updateValue("heiter, mäßiger Sprühregen", forKey: "1;52")
        dict.updateValue("heiter, mäßiger Sprühregen", forKey: "1;53")
        dict.updateValue("heiter, starker Sprühregen", forKey: "1;54")
        dict.updateValue("heiter, starker Sprühregen", forKey: "1;55")
        dict.updateValue("heiter, Sprühregen mit Glatteisgefahr", forKey: "1;56")
        dict.updateValue("heiter, Sprühregen mit Glatteisgefahr", forKey: "1;57")
        dict.updateValue("heiter, Sprühregen mit Regen", forKey: "1;58")
        dict.updateValue("heiter, Sprühregen mit Regen", forKey: "1;59")
        dict.updateValue("heiter, leichter Regen", forKey: "1;60")
        dict.updateValue("heiter, leichter Regen", forKey: "1;61")
        dict.updateValue("heiter, mäßiger Regen", forKey: "1;62")
        dict.updateValue("heiter, mäßiger Regen", forKey: "1;63")
        dict.updateValue("heiter, starker Regen", forKey: "1;64")
        dict.updateValue("heiter, starker Regen", forKey: "1;65")
        dict.updateValue("heiter, Regen mit Glatteisgefahr", forKey: "1;66")
        dict.updateValue("heiter, Regen mit Glatteisgefahr", forKey: "1;67")
        dict.updateValue("heiter, Schneeregen", forKey: "1;68")
        dict.updateValue("heiter, Schneeregen", forKey: "1;69")
        dict.updateValue("heiter, leichter Schneefall", forKey: "1;70")
        dict.updateValue("heiter, leichter Schneefall", forKey: "1;71")
        dict.updateValue("heiter, mäßiger Schneefall", forKey: "1;72")
        dict.updateValue("heiter, mäßiger Schneefall", forKey: "1;73")
        dict.updateValue("heiter, starker Schneefall", forKey: "1;74")
        dict.updateValue("heiter, starker Schneefall", forKey: "1;75")
        dict.updateValue("heiter, Eisnadeln", forKey: "1;76")
        dict.updateValue("heiter, Schneegriesel", forKey: "1;77")
        dict.updateValue("heiter, Eisnadeln", forKey: "1;78")
        dict.updateValue("heiter", forKey: "1;79")
        dict.updateValue("heiter, Regenschauer", forKey: "1;80")
        dict.updateValue("heiter, Regenschauer", forKey: "1;81")
        dict.updateValue("heiter, Regenschauer", forKey: "1;82")
        dict.updateValue("heiter, Schneeregenschauer", forKey: "1;83")
        dict.updateValue("heiter, Schneeregenschauer", forKey: "1;84")
        dict.updateValue("heiter, Schneeschauer", forKey: "1;85")
        dict.updateValue("heiter, Schneeschauer", forKey: "1;86")
        dict.updateValue("heiter, Graupelschauer", forKey: "1;87")
        dict.updateValue("heiter, Graupelschauer", forKey: "1;88")
        dict.updateValue("heiter, Hagelschauer", forKey: "1;89")
        dict.updateValue("heiter, Hagelschauer", forKey: "1;90")
        dict.updateValue("heiter, Gewitter", forKey: "1;91")
        dict.updateValue("heiter, Gewitter", forKey: "1;92")
        dict.updateValue("heiter, Graupelgewitter", forKey: "1;93")
        dict.updateValue("heiter, Graupelgewitter", forKey: "1;94")
        dict.updateValue("heiter, Gewitter", forKey: "1;95")
        dict.updateValue("heiter, Graupelgewitter", forKey: "1;96")
        dict.updateValue("heiter, Gewitter", forKey: "1;97")
        dict.updateValue("heiter, Gewitter mit Staubsturm", forKey: "1;98")
        dict.updateValue("heiter, starkes Graupelgewitter", forKey: "1;99")
        dict.updateValue("heiter, Schleierwolken", forKey: "2;-8")
        dict.updateValue("heiter, Schneesturm", forKey: "2;-7")
        dict.updateValue("heiter, Sturm", forKey: "2;-6")
        dict.updateValue("heiter, Glatteisgefahr", forKey: "2;-5")
        dict.updateValue("heiter, Nebel", forKey: "2;-4")
        dict.updateValue("heiter, Schnee", forKey: "2;-3")
        dict.updateValue("heiter, Regen", forKey: "2;-2")
        dict.updateValue("heiter, Regen", forKey: "2;-1")
        dict.updateValue("heiter", forKey: "2;0")
        dict.updateValue("heiter", forKey: "2;1")
        dict.updateValue("heiter", forKey: "2;2")
        dict.updateValue("heiter", forKey: "2;3")
        dict.updateValue("heiter", forKey: "2;4")
        dict.updateValue("heiter", forKey: "2;5")
        dict.updateValue("heiter", forKey: "2;6")
        dict.updateValue("heiter", forKey: "2;7")
        dict.updateValue("heiter", forKey: "2;8")
        dict.updateValue("heiter", forKey: "2;9")
        dict.updateValue("heiter, dunstig", forKey: "2;10")
        dict.updateValue("heiter, Bodennebel", forKey: "2;11")
        dict.updateValue("heiter, Bodennebel", forKey: "2;12")
        dict.updateValue("heiter, Wetterleuchten", forKey: "2;13")
        dict.updateValue("heiter, Tropfen möglich", forKey: "2;14")
        dict.updateValue("heiter, etwas Regen", forKey: "2;15")
        dict.updateValue("heiter, etwas Regen", forKey: "2;16")
        dict.updateValue("heiter, gewittrig", forKey: "2;17")
        dict.updateValue("heiter, böig", forKey: "2;18")
        dict.updateValue("heiter, Tornado", forKey: "2;19")
        dict.updateValue("heiter, Sprühregen", forKey: "2;20")
        dict.updateValue("heiter, Regen", forKey: "2;21")
        dict.updateValue("heiter, Schneefall", forKey: "2;22")
        dict.updateValue("heiter, Schneeregen", forKey: "2;23")
        dict.updateValue("heiter, Schneeregen mit Glatteisgefahr", forKey: "2;24")
        dict.updateValue("heiter, Regenschauer", forKey: "2;25")
        dict.updateValue("heiter, Schneeschauer", forKey: "2;26")
        dict.updateValue("heiter, Graupelschauer", forKey: "2;27")
        dict.updateValue("heiter, Nebel", forKey: "2;28")
        dict.updateValue("heiter, gewittrig", forKey: "2;29")
        dict.updateValue("heiter, Staubsturm", forKey: "2;30")
        dict.updateValue("heiter, Staubsturm", forKey: "2;31")
        dict.updateValue("heiter, Staubsturm", forKey: "2;32")
        dict.updateValue("heiter, Staubsturm", forKey: "2;33")
        dict.updateValue("heiter, Staubsturm", forKey: "2;34")
        dict.updateValue("heiter, Staubsturm", forKey: "2;35")
        dict.updateValue("heiter, Schneefegen", forKey: "2;36")
        dict.updateValue("heiter, Schneefegen", forKey: "2;37")
        dict.updateValue("heiter, Schneetreiben", forKey: "2;38")
        dict.updateValue("heiter, Schneetreiben", forKey: "2;39")
        dict.updateValue("heiter, Nebel", forKey: "2;40")
        dict.updateValue("heiter, Nebeltreiben", forKey: "2;41")
        dict.updateValue("heiter, Nebel", forKey: "2;42")
        dict.updateValue("heiter, Nebel", forKey: "2;43")
        dict.updateValue("heiter, Nebel", forKey: "2;44")
        dict.updateValue("heiter, Nebel", forKey: "2;45")
        dict.updateValue("heiter, Nebel", forKey: "2;46")
        dict.updateValue("heiter, Nebel", forKey: "2;47")
        dict.updateValue("heiter, Eisnebel", forKey: "2;48")
        dict.updateValue("heiter, Eisnebel", forKey: "2;49")
        dict.updateValue("heiter, leichter Sprühregen", forKey: "2;50")
        dict.updateValue("heiter, leichter Sprühregen", forKey: "2;51")
        dict.updateValue("heiter, mäßiger Sprühregen", forKey: "2;52")
        dict.updateValue("heiter, mäßiger Sprühregen", forKey: "2;53")
        dict.updateValue("heiter, starker Sprühregen", forKey: "2;54")
        dict.updateValue("heiter, starker Sprühregen", forKey: "2;55")
        dict.updateValue("heiter, Sprühregen mit Glatteisgefahr", forKey: "2;56")
        dict.updateValue("heiter, Sprühregen mit Glatteisgefahr", forKey: "2;57")
        dict.updateValue("heiter, Sprühregen mit Regen", forKey: "2;58")
        dict.updateValue("heiter, Sprühregen mit Regen", forKey: "2;59")
        dict.updateValue("heiter, leichter Regen", forKey: "2;60")
        dict.updateValue("heiter, leichter Regen", forKey: "2;61")
        dict.updateValue("heiter, mäßiger Regen", forKey: "2;62")
        dict.updateValue("heiter, mäßiger Regen", forKey: "2;63")
        dict.updateValue("heiter, starker Regen", forKey: "2;64")
        dict.updateValue("heiter, starker Regen", forKey: "2;65")
        dict.updateValue("heiter, Regen mit Glatteisgefahr", forKey: "2;66")
        dict.updateValue("heiter, Regen mit Glatteisgefahr", forKey: "2;67")
        dict.updateValue("heiter, Schneeregen", forKey: "2;68")
        dict.updateValue("heiter, Schneeregen", forKey: "2;69")
        dict.updateValue("heiter, leichter Schneefall", forKey: "2;70")
        dict.updateValue("heiter, leichter Schneefall", forKey: "2;71")
        dict.updateValue("heiter, mäßiger Schneefall", forKey: "2;72")
        dict.updateValue("heiter, mäßiger Schneefall", forKey: "2;73")
        dict.updateValue("heiter, starker Schneefall", forKey: "2;74")
        dict.updateValue("heiter, starker Schneefall", forKey: "2;75")
        dict.updateValue("heiter, Eisnadeln", forKey: "2;76")
        dict.updateValue("heiter, Schneegriesel", forKey: "2;77")
        dict.updateValue("heiter, Eisnadeln", forKey: "2;78")
        dict.updateValue("heiter, Eiskörner", forKey: "2;79")
        dict.updateValue("heiter, Regenschauer", forKey: "2;80")
        dict.updateValue("heiter, Regenschauer", forKey: "2;81")
        dict.updateValue("heiter, Regenschauer", forKey: "2;82")
        dict.updateValue("heiter, Schneeregenschauer", forKey: "2;83")
        dict.updateValue("heiter, Schneeregenschauer", forKey: "2;84")
        dict.updateValue("heiter, Schneeschauer", forKey: "2;85")
        dict.updateValue("heiter, Schneeschauer", forKey: "2;86")
        dict.updateValue("heiter, Graupelschauer", forKey: "2;87")
        dict.updateValue("heiter, Graupelschauer", forKey: "2;88")
        dict.updateValue("heiter, Hagelschauer", forKey: "2;89")
        dict.updateValue("heiter, Hagelschauer", forKey: "2;90")
        dict.updateValue("heiter, Gewitter", forKey: "2;91")
        dict.updateValue("heiter, Gewitter", forKey: "2;92")
        dict.updateValue("heiter, Graupelgewitter", forKey: "2;93")
        dict.updateValue("heiter, Graupelgewitter", forKey: "2;94")
        dict.updateValue("heiter, Gewitter", forKey: "2;95")
        dict.updateValue("heiter, Graupelgewitter", forKey: "2;96")
        dict.updateValue("heiter, Gewitter", forKey: "2;97")
        dict.updateValue("heiter, Gewitter mit Staubsturm", forKey: "2;98")
        dict.updateValue("heiter, starkes Graupelgewitter", forKey: "2;99")
        dict.updateValue("heiter, Schleierwolken", forKey: "3;-8")
        dict.updateValue("heiter, Schneesturm", forKey: "3;-7")
        dict.updateValue("heiter, stürmisch", forKey: "3;-6")
        dict.updateValue("heiter, Glatteisgefahr", forKey: "3;-5")
        dict.updateValue("heiter, Nebel", forKey: "3;-4")
        dict.updateValue("heiter, Schnee", forKey: "3;-3")
        dict.updateValue("heiter, Regen", forKey: "3;-2")
        dict.updateValue("heiter, Regen", forKey: "3;-1")
        dict.updateValue("heiter", forKey: "3;0")
        dict.updateValue("heiter", forKey: "3;1")
        dict.updateValue("heiter", forKey: "3;2")
        dict.updateValue("heiter", forKey: "3;3")
        dict.updateValue("heiter", forKey: "3;4")
        dict.updateValue("heiter", forKey: "3;5")
        dict.updateValue("heiter", forKey: "3;6")
        dict.updateValue("heiter", forKey: "3;7")
        dict.updateValue("heiter", forKey: "3;8")
        dict.updateValue("heiter", forKey: "3;9")
        dict.updateValue("heiter, dunstig", forKey: "3;10")
        dict.updateValue("heiter, Bodennebel", forKey: "3;11")
        dict.updateValue("heiter, Bodennebel", forKey: "3;12")
        dict.updateValue("heiter, Wetterleuchten", forKey: "3;13")
        dict.updateValue("heiter, Tropfen möglich", forKey: "3;14")
        dict.updateValue("heiter, etwas Regen", forKey: "3;15")
        dict.updateValue("heiter, etwas Regen", forKey: "3;16")
        dict.updateValue("heiter, gewittrig", forKey: "3;17")
        dict.updateValue("heiter, böig", forKey: "3;18")
        dict.updateValue("heiter, Tornado", forKey: "3;19")
        dict.updateValue("heiter, Sprühregen", forKey: "3;20")
        dict.updateValue("heiter, Regen", forKey: "3;21")
        dict.updateValue("heiter, Schneefall", forKey: "3;22")
        dict.updateValue("heiter, Schneeregen", forKey: "3;23")
        dict.updateValue("heiter, Schneeregen mit Glatteisgefahr", forKey: "3;24")
        dict.updateValue("heiter, Regenschauer", forKey: "3;25")
        dict.updateValue("heiter, Schneeschauer", forKey: "3;26")
        dict.updateValue("heiter, Graupelschauer", forKey: "3;27")
        dict.updateValue("heiter, Nebel", forKey: "3;28")
        dict.updateValue("heiter, gewittrig", forKey: "3;29")
        dict.updateValue("heiter, Staubsturm", forKey: "3;30")
        dict.updateValue("heiter, Staubsturm", forKey: "3;31")
        dict.updateValue("heiter, Staubsturm", forKey: "3;32")
        dict.updateValue("heiter, Staubsturm", forKey: "3;33")
        dict.updateValue("heiter, Staubsturm", forKey: "3;34")
        dict.updateValue("heiter, Staubsturm", forKey: "3;35")
        dict.updateValue("heiter, Schneefegen", forKey: "3;36")
        dict.updateValue("heiter, Schneefegen", forKey: "3;37")
        dict.updateValue("heiter, Schneetreiben", forKey: "3;38")
        dict.updateValue("heiter, Schneetreiben", forKey: "3;39")
        dict.updateValue("heiter, Nebel", forKey: "3;40")
        dict.updateValue("heiter, Nebeltreiben", forKey: "3;41")
        dict.updateValue("heiter, Nebel", forKey: "3;42")
        dict.updateValue("heiter, Nebel", forKey: "3;43")
        dict.updateValue("heiter, Nebel", forKey: "3;44")
        dict.updateValue("heiter, Nebel", forKey: "3;45")
        dict.updateValue("heiter, Nebel", forKey: "3;46")
        dict.updateValue("heiter, Nebel", forKey: "3;47")
        dict.updateValue("heiter, Eisnebel", forKey: "3;48")
        dict.updateValue("heiter, Eisnebel", forKey: "3;49")
        dict.updateValue("heiter, leichter Sprühregen", forKey: "3;50")
        dict.updateValue("heiter, leichter Sprühregen", forKey: "3;51")
        dict.updateValue("heiter, mäßiger Sprühregen", forKey: "3;52")
        dict.updateValue("heiter, mäßiger Sprühregen", forKey: "3;53")
        dict.updateValue("heiter, starker Sprühregen", forKey: "3;54")
        dict.updateValue("heiter, starker Sprühregen", forKey: "3;55")
        dict.updateValue("heiter, Sprühregen mit Glatteisgefahr", forKey: "3;56")
        dict.updateValue("heiter, Sprühregen mit Glatteisgefahr", forKey: "3;57")
        dict.updateValue("heiter, Sprühregen mit Regen", forKey: "3;58")
        dict.updateValue("heiter, Sprühregen mit Regen", forKey: "3;59")
        dict.updateValue("heiter, leichter Regen", forKey: "3;60")
        dict.updateValue("heiter, leichter Regen", forKey: "3;61")
        dict.updateValue("heiter, mäßiger Regen", forKey: "3;62")
        dict.updateValue("heiter, mäßiger Regen", forKey: "3;63")
        dict.updateValue("heiter, starker Regen", forKey: "3;64")
        dict.updateValue("heiter, starker Regen", forKey: "3;65")
        dict.updateValue("heiter, Regen mit Glatteisgefahr", forKey: "3;66")
        dict.updateValue("heiter, Regen mit Glatteisgefahr", forKey: "3;67")
        dict.updateValue("heiter, Schneeregen", forKey: "3;68")
        dict.updateValue("heiter, Schneeregen", forKey: "3;69")
        dict.updateValue("heiter, leichter Schneefall", forKey: "3;70")
        dict.updateValue("heiter, leichter Schneefall", forKey: "3;71")
        dict.updateValue("heiter, mäßiger Schneefall", forKey: "3;72")
        dict.updateValue("heiter, mäßiger Schneefall", forKey: "3;73")
        dict.updateValue("heiter, starker Schneefall", forKey: "3;74")
        dict.updateValue("heiter, starker Schneefall", forKey: "3;75")
        dict.updateValue("heiter, Eisnadeln", forKey: "3;76")
        dict.updateValue("heiter, Schneegriesel", forKey: "3;77")
        dict.updateValue("heiter, Eisnadeln", forKey: "3;78")
        dict.updateValue("heiter, Eiskörner", forKey: "3;79")
        dict.updateValue("heiter, Regenschauer", forKey: "3;80")
        dict.updateValue("heiter, Regenschauer", forKey: "3;81")
        dict.updateValue("heiter, Regenschauer", forKey: "3;82")
        dict.updateValue("heiter, Schneeregenschauer", forKey: "3;83")
        dict.updateValue("heiter, Schneeregenschauer", forKey: "3;84")
        dict.updateValue("heiter, Schneeschauer", forKey: "3;85")
        dict.updateValue("heiter, Schneeschauer", forKey: "3;86")
        dict.updateValue("heiter, Graupelschauer", forKey: "3;87")
        dict.updateValue("heiter, Graupelschauer", forKey: "3;88")
        dict.updateValue("heiter, Hagelschauer", forKey: "3;89")
        dict.updateValue("heiter, Hagelschauer", forKey: "3;90")
        dict.updateValue("heiter, Gewitter", forKey: "3;91")
        dict.updateValue("heiter, Gewitter", forKey: "3;92")
        dict.updateValue("heiter, Graupelgewitter", forKey: "3;93")
        dict.updateValue("heiter, Graupelgewitter", forKey: "3;94")
        dict.updateValue("heiter, Gewitter", forKey: "3;95")
        dict.updateValue("heiter, Graupelgewitter", forKey: "3;96")
        dict.updateValue("heiter, Gewitter", forKey: "3;97")
        dict.updateValue("heiter, Gewitter mit Staubsturm", forKey: "3;98")
        dict.updateValue("heiter, starkes Graupelgewitter", forKey: "3;99")
        dict.updateValue("wolkig, Schleierwolken", forKey: "4;-8")
        dict.updateValue("wolkig, Schneesturm", forKey: "4;-7")
        dict.updateValue("wolkig, Sturm", forKey: "4;-6")
        dict.updateValue("wolkig, Glatteisgefahr", forKey: "4;-5")
        dict.updateValue("wolkig, dichter Nebel", forKey: "4;-4")
        dict.updateValue("wolkig, Schneefall", forKey: "4;-3")
        dict.updateValue("wolkig, Regenwolken", forKey: "4;-2")
        dict.updateValue("wolkig, Regenwolken", forKey: "4;-1")
        dict.updateValue("wolkig", forKey: "4;0")
        dict.updateValue("wolkig", forKey: "4;1")
        dict.updateValue("wolkig", forKey: "4;2")
        dict.updateValue("wolkig", forKey: "4;3")
        dict.updateValue("wolkig", forKey: "4;4")
        dict.updateValue("wolkig", forKey: "4;5")
        dict.updateValue("wolkig", forKey: "4;6")
        dict.updateValue("wolkig", forKey: "4;7")
        dict.updateValue("wolkig", forKey: "4;8")
        dict.updateValue("wolkig", forKey: "4;9")
        dict.updateValue("wolkig, dunstig", forKey: "4;10")
        dict.updateValue("wolkig, Bodennebel", forKey: "4;11")
        dict.updateValue("wolkig, Bodennebel", forKey: "4;12")
        dict.updateValue("wolkig, Wetterleuchten", forKey: "4;13")
        dict.updateValue("wolkig, Tropfen möglich", forKey: "4;14")
        dict.updateValue("wolkig, etwas Regen", forKey: "4;15")
        dict.updateValue("wolkig, etwas Regen", forKey: "4;16")
        dict.updateValue("wolkig, gewittrig", forKey: "4;17")
        dict.updateValue("wolkig, böig", forKey: "4;18")
        dict.updateValue("wolkig, Tornado", forKey: "4;19")
        dict.updateValue("wolkig, Sprühregen", forKey: "4;20")
        dict.updateValue("wolkig, Regen", forKey: "4;21")
        dict.updateValue("wolkig, Schneefall", forKey: "4;22")
        dict.updateValue("wolkig, Schneeregen", forKey: "4;23")
        dict.updateValue("wolkig, Schneeregen mit Glatteisgefahr", forKey: "4;24")
        dict.updateValue("wolkig, Regenschauer", forKey: "4;25")
        dict.updateValue("wolkig, Schneeschauer", forKey: "4;26")
        dict.updateValue("wolkig, Graupelschauer", forKey: "4;27")
        dict.updateValue("wolkig, Nebel", forKey: "4;28")
        dict.updateValue("wolkig, gewittrig", forKey: "4;29")
        dict.updateValue("wolkig, Staubsturm", forKey: "4;30")
        dict.updateValue("wolkig, Staubsturm", forKey: "4;31")
        dict.updateValue("wolkig, Staubsturm", forKey: "4;32")
        dict.updateValue("wolkig, Staubsturm", forKey: "4;33")
        dict.updateValue("wolkig, Staubsturm", forKey: "4;34")
        dict.updateValue("wolkig, Staubsturm", forKey: "4;35")
        dict.updateValue("wolkig, Schneefegen", forKey: "4;36")
        dict.updateValue("wolkig, Schneefegen", forKey: "4;37")
        dict.updateValue("wolkig, Schneetreiben", forKey: "4;38")
        dict.updateValue("wolkig, Schneetreiben", forKey: "4;39")
        dict.updateValue("wolkig, Nebel", forKey: "4;40")
        dict.updateValue("wolkig, Nebeltreiben", forKey: "4;41")
        dict.updateValue("wolkig, Nebel", forKey: "4;42")
        dict.updateValue("wolkig, Nebel", forKey: "4;43")
        dict.updateValue("wolkig, Nebel", forKey: "4;44")
        dict.updateValue("wolkig, Nebel", forKey: "4;45")
        dict.updateValue("wolkig, Nebel", forKey: "4;46")
        dict.updateValue("wolkig, Nebel", forKey: "4;47")
        dict.updateValue("wolkig, Eisnebel", forKey: "4;48")
        dict.updateValue("wolkig, Eisnebel", forKey: "4;49")
        dict.updateValue("wolkig, leichter Sprühregen", forKey: "4;50")
        dict.updateValue("wolkig, leichter Sprühregen", forKey: "4;51")
        dict.updateValue("wolkig, mäßiger Sprühregen", forKey: "4;52")
        dict.updateValue("wolkig, mäßiger Sprühregen", forKey: "4;53")
        dict.updateValue("wolkig, starker Sprühregen", forKey: "4;54")
        dict.updateValue("wolkig, starker Sprühregen", forKey: "4;55")
        dict.updateValue("wolkig, Sprühregen mit Glatteisgefahr", forKey: "4;56")
        dict.updateValue("wolkig, Sprühregen mit Glatteisgefahr", forKey: "4;57")
        dict.updateValue("wolkig, Sprühregen mit Regen", forKey: "4;58")
        dict.updateValue("wolkig, Sprühregen mit Regen", forKey: "4;59")
        dict.updateValue("wolkig, leichter Regen", forKey: "4;60")
        dict.updateValue("wolkig, leichter Regen", forKey: "4;61")
        dict.updateValue("wolkig, mäßiger Regen", forKey: "4;62")
        dict.updateValue("wolkig, mäßiger Regen", forKey: "4;63")
        dict.updateValue("wolkig, starker Regen", forKey: "4;64")
        dict.updateValue("wolkig, starker Regen", forKey: "4;65")
        dict.updateValue("wolkig, Regen mit Glatteisgefahr", forKey: "4;66")
        dict.updateValue("wolkig, Regen mit Glatteisgefahr", forKey: "4;67")
        dict.updateValue("wolkig, Schneeregen", forKey: "4;68")
        dict.updateValue("wolkig, Schneeregen", forKey: "4;69")
        dict.updateValue("wolkig, leichter Schneefall", forKey: "4;70")
        dict.updateValue("wolkig, leichter Schneefall", forKey: "4;71")
        dict.updateValue("wolkig, mäßiger Schneefall", forKey: "4;72")
        dict.updateValue("wolkig, mäßiger Schneefall", forKey: "4;73")
        dict.updateValue("wolkig, starker Schneefall", forKey: "4;74")
        dict.updateValue("wolkig, starker Schneefall", forKey: "4;75")
        dict.updateValue("wolkig, Eisnadeln", forKey: "4;76")
        dict.updateValue("wolkig, Schneegriesel", forKey: "4;77")
        dict.updateValue("wolkig, Eisnadeln", forKey: "4;78")
        dict.updateValue("wolkig, Eiskörner", forKey: "4;79")
        dict.updateValue("wolkig, Regenschauer", forKey: "4;80")
        dict.updateValue("wolkig, Regenschauer", forKey: "4;81")
        dict.updateValue("wolkig, Regenschauer", forKey: "4;82")
        dict.updateValue("wolkig, Schneeregenschauer", forKey: "4;83")
        dict.updateValue("wolkig, Schneeregenschauer", forKey: "4;84")
        dict.updateValue("wolkig, Schneeschauer", forKey: "4;85")
        dict.updateValue("wolkig, Schneeschauer", forKey: "4;86")
        dict.updateValue("wolkig, Graupelschauer", forKey: "4;87")
        dict.updateValue("wolkig, Graupelschauer", forKey: "4;88")
        dict.updateValue("wolkig, Hagelschauer", forKey: "4;89")
        dict.updateValue("wolkig, Hagelschauer", forKey: "4;90")
        dict.updateValue("wolkig, Gewitter", forKey: "4;91")
        dict.updateValue("wolkig, Gewitter", forKey: "4;92")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "4;93")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "4;94")
        dict.updateValue("wolkig, Gewitter", forKey: "4;95")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "4;96")
        dict.updateValue("wolkig, Gewitter", forKey: "4;97")
        dict.updateValue("wolkig, Gewitter mit Staubsturm", forKey: "4;98")
        dict.updateValue("wolkig, starkes Graupelgewitter", forKey: "4;99")
        dict.updateValue("wolkig, Schleierwolken", forKey: "5;-8")
        dict.updateValue("wolkig, Schneesturm", forKey: "5;-7")
        dict.updateValue("wolkig, Sturm", forKey: "5;-6")
        dict.updateValue("wolkig, Glatteisgefahr", forKey: "5;-5")
        dict.updateValue("wolkig, dichter Nebel", forKey: "5;-4")
        dict.updateValue("wolkig, Schneefall", forKey: "5;-3")
        dict.updateValue("wolkig, Regenwolken", forKey: "5;-2")
        dict.updateValue("wolkig, Regenwolken", forKey: "5;-1")
        dict.updateValue("wolkig", forKey: "5;0")
        dict.updateValue("wolkig", forKey: "5;1")
        dict.updateValue("wolkig", forKey: "5;2")
        dict.updateValue("wolkig", forKey: "5;3")
        dict.updateValue("wolkig", forKey: "5;4")
        dict.updateValue("wolkig", forKey: "5;5")
        dict.updateValue("wolkig", forKey: "5;6")
        dict.updateValue("wolkig", forKey: "5;7")
        dict.updateValue("wolkig", forKey: "5;8")
        dict.updateValue("wolkig", forKey: "5;9")
        dict.updateValue("wolkig, dunstig", forKey: "5;10")
        dict.updateValue("wolkig, Bodennebel", forKey: "5;11")
        dict.updateValue("wolkig, Bodennebel", forKey: "5;12")
        dict.updateValue("wolkig, Wetterleuchten", forKey: "5;13")
        dict.updateValue("wolkig, Tropfen möglich", forKey: "5;14")
        dict.updateValue("wolkig, etwas Regen", forKey: "5;15")
        dict.updateValue("wolkig, etwas Regen", forKey: "5;16")
        dict.updateValue("wolkig, gewittrig", forKey: "5;17")
        dict.updateValue("wolkig, böig", forKey: "5;18")
        dict.updateValue("wolkig, Tornado", forKey: "5;19")
        dict.updateValue("wolkig, Sprühregen", forKey: "5;20")
        dict.updateValue("wolkig, Regen", forKey: "5;21")
        dict.updateValue("wolkig, Schneefall", forKey: "5;22")
        dict.updateValue("wolkig, Schneeregen", forKey: "5;23")
        dict.updateValue("wolkig, Schneeregen mit Glatteisgefahr", forKey: "5;24")
        dict.updateValue("wolkig, Regenschauer", forKey: "5;25")
        dict.updateValue("wolkig, Schneeschauer", forKey: "5;26")
        dict.updateValue("wolkig, Graupelschauer", forKey: "5;27")
        dict.updateValue("wolkig, Nebel", forKey: "5;28")
        dict.updateValue("wolkig, gewittrig", forKey: "5;29")
        dict.updateValue("wolkig, Staubsturm", forKey: "5;30")
        dict.updateValue("wolkig, Staubsturm", forKey: "5;31")
        dict.updateValue("wolkig, Staubsturm", forKey: "5;32")
        dict.updateValue("wolkig, Staubsturm", forKey: "5;33")
        dict.updateValue("wolkig, Staubsturm", forKey: "5;34")
        dict.updateValue("wolkig, Staubsturm", forKey: "5;35")
        dict.updateValue("wolkig, Schneefegen", forKey: "5;36")
        dict.updateValue("wolkig, Schneefegen", forKey: "5;37")
        dict.updateValue("wolkig, Schneetreiben", forKey: "5;38")
        dict.updateValue("wolkig, Schneetreiben", forKey: "5;39")
        dict.updateValue("wolkig, Nebel", forKey: "5;40")
        dict.updateValue("wolkig, Nebeltreiben", forKey: "5;41")
        dict.updateValue("wolkig, Nebel", forKey: "5;42")
        dict.updateValue("wolkig, Nebel", forKey: "5;43")
        dict.updateValue("wolkig, Nebel", forKey: "5;44")
        dict.updateValue("wolkig, Nebel", forKey: "5;45")
        dict.updateValue("wolkig, Nebel", forKey: "5;46")
        dict.updateValue("wolkig, Nebel", forKey: "5;47")
        dict.updateValue("wolkig, Eisnebel", forKey: "5;48")
        dict.updateValue("wolkig, Eisnebel", forKey: "5;49")
        dict.updateValue("wolkig, leichter Sprühregen", forKey: "5;50")
        dict.updateValue("wolkig, leichter Sprühregen", forKey: "5;51")
        dict.updateValue("wolkig, mäßiger Sprühregen", forKey: "5;52")
        dict.updateValue("wolkig, mäßiger Sprühregen", forKey: "5;53")
        dict.updateValue("wolkig, starker Sprühregen", forKey: "5;54")
        dict.updateValue("wolkig, starker Sprühregen", forKey: "5;55")
        dict.updateValue("wolkig, Sprühregen mit Glatteisgefahr", forKey: "5;56")
        dict.updateValue("wolkig, Sprühregen mit Glatteisgefahr", forKey: "5;57")
        dict.updateValue("wolkig, Sprühregen mit Regen", forKey: "5;58")
        dict.updateValue("wolkig, Sprühregen mit Regen", forKey: "5;59")
        dict.updateValue("wolkig, leichter Regen", forKey: "5;60")
        dict.updateValue("wolkig, leichter Regen", forKey: "5;61")
        dict.updateValue("wolkig, mäßiger Regen", forKey: "5;62")
        dict.updateValue("wolkig, mäßiger Regen", forKey: "5;63")
        dict.updateValue("wolkig, starker Regen", forKey: "5;64")
        dict.updateValue("wolkig, starker Regen", forKey: "5;65")
        dict.updateValue("wolkig, Regen mit Glatteisgefahr", forKey: "5;66")
        dict.updateValue("wolkig, Regen mit Glatteisgefahr", forKey: "5;67")
        dict.updateValue("wolkig, Schneeregen", forKey: "5;68")
        dict.updateValue("wolkig, Schneeregen", forKey: "5;69")
        dict.updateValue("wolkig, leichter Schneefall", forKey: "5;70")
        dict.updateValue("wolkig, leichter Schneefall", forKey: "5;71")
        dict.updateValue("wolkig, mäßiger Schneefall", forKey: "5;72")
        dict.updateValue("wolkig, mäßiger Schneefall", forKey: "5;73")
        dict.updateValue("wolkig, starker Schneefall", forKey: "5;74")
        dict.updateValue("wolkig, starker Schneefall", forKey: "5;75")
        dict.updateValue("wolkig, Eisnadeln", forKey: "5;76")
        dict.updateValue("wolkig, Schneegriesel", forKey: "5;77")
        dict.updateValue("wolkig, Eisnadeln", forKey: "5;78")
        dict.updateValue("wolkig, Eiskörner", forKey: "5;79")
        dict.updateValue("wolkig, Regenschauer", forKey: "5;80")
        dict.updateValue("wolkig, Regenschauer", forKey: "5;81")
        dict.updateValue("wolkig, Regenschauer", forKey: "5;82")
        dict.updateValue("wolkig, Schneeregenschauer", forKey: "5;83")
        dict.updateValue("wolkig, Schneeregenschauer", forKey: "5;84")
        dict.updateValue("wolkig, Schneeschauer", forKey: "5;85")
        dict.updateValue("wolkig, Schneeschauer", forKey: "5;86")
        dict.updateValue("wolkig, Graupelschauer", forKey: "5;87")
        dict.updateValue("wolkig, Graupelschauer", forKey: "5;88")
        dict.updateValue("wolkig, Hagelschauer", forKey: "5;89")
        dict.updateValue("wolkig, Hagelschauer", forKey: "5;90")
        dict.updateValue("wolkig, Gewitter", forKey: "5;91")
        dict.updateValue("wolkig, Gewitter", forKey: "5;92")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "5;93")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "5;94")
        dict.updateValue("wolkig, Gewitter", forKey: "5;95")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "5;96")
        dict.updateValue("wolkig, Gewitter", forKey: "5;97")
        dict.updateValue("wolkig, Gewitter mit Staubsturm", forKey: "5;98")
        dict.updateValue("wolkig, starkes Graupelgewitter", forKey: "5;99")
        dict.updateValue("wolkig, Schleierwolken", forKey: "6;-8")
        dict.updateValue("wolkig, Schneesturm", forKey: "6;-7")
        dict.updateValue("wolkig, Sturm", forKey: "6;-6")
        dict.updateValue("wolkig, Glatteisgefahr", forKey: "6;-5")
        dict.updateValue("wolkig, neblig", forKey: "6;-4")
        dict.updateValue("wolkig, Schneefall", forKey: "6;-3")
        dict.updateValue("wolkig, Regenwolken", forKey: "6;-2")
        dict.updateValue("wolkig, Regenwolken", forKey: "6;-1")
        dict.updateValue("wolkig", forKey: "6;0")
        dict.updateValue("wolkig", forKey: "6;1")
        dict.updateValue("wolkig", forKey: "6;2")
        dict.updateValue("wolkig", forKey: "6;3")
        dict.updateValue("wolkig", forKey: "6;4")
        dict.updateValue("wolkig", forKey: "6;5")
        dict.updateValue("wolkig", forKey: "6;6")
        dict.updateValue("wolkig", forKey: "6;7")
        dict.updateValue("wolkig", forKey: "6;8")
        dict.updateValue("wolkig", forKey: "6;9")
        dict.updateValue("wolkig, dunstig", forKey: "6;10")
        dict.updateValue("wolkig, Bodennebel", forKey: "6;11")
        dict.updateValue("wolkig, Bodennebel", forKey: "6;12")
        dict.updateValue("wolkig, Wetterleuchten", forKey: "6;13")
        dict.updateValue("wolkig, Tropfen möglich", forKey: "6;14")
        dict.updateValue("wolkig, etwas Regen", forKey: "6;15")
        dict.updateValue("wolkig, etwas Regen", forKey: "6;16")
        dict.updateValue("wolkig, gewittrig", forKey: "6;17")
        dict.updateValue("wolkig, böig", forKey: "6;18")
        dict.updateValue("wolkig, Tornado", forKey: "6;19")
        dict.updateValue("wolkig, Sprühregen", forKey: "6;20")
        dict.updateValue("wolkig, Regen", forKey: "6;21")
        dict.updateValue("wolkig, Schneefall", forKey: "6;22")
        dict.updateValue("wolkig, Schneeregen", forKey: "6;23")
        dict.updateValue("wolkig, Schneeregen mit Glatteisgefahr", forKey: "6;24")
        dict.updateValue("wolkig, Regenschauer", forKey: "6;25")
        dict.updateValue("wolkig, Schneeschauer", forKey: "6;26")
        dict.updateValue("wolkig, Graupelschauer", forKey: "6;27")
        dict.updateValue("wolkig, Nebel", forKey: "6;28")
        dict.updateValue("wolkig, gewittrig", forKey: "6;29")
        dict.updateValue("wolkig, Staubsturm", forKey: "6;30")
        dict.updateValue("wolkig, Staubsturm", forKey: "6;31")
        dict.updateValue("wolkig, Staubsturm", forKey: "6;32")
        dict.updateValue("wolkig, Staubsturm", forKey: "6;33")
        dict.updateValue("wolkig, Staubsturm", forKey: "6;34")
        dict.updateValue("wolkig, Staubsturm", forKey: "6;35")
        dict.updateValue("wolkig, Schneefegen", forKey: "6;36")
        dict.updateValue("wolkig, Schneefegen", forKey: "6;37")
        dict.updateValue("wolkig, Schneetreiben", forKey: "6;38")
        dict.updateValue("wolkig, Schneetreiben", forKey: "6;39")
        dict.updateValue("wolkig, Nebel", forKey: "6;40")
        dict.updateValue("wolkig, Nebeltreiben", forKey: "6;41")
        dict.updateValue("wolkig, Nebel", forKey: "6;42")
        dict.updateValue("wolkig, Nebel", forKey: "6;43")
        dict.updateValue("wolkig, Nebel", forKey: "6;44")
        dict.updateValue("wolkig, Nebel", forKey: "6;45")
        dict.updateValue("wolkig, Nebel", forKey: "6;46")
        dict.updateValue("wolkig, Nebel", forKey: "6;47")
        dict.updateValue("wolkig, Eisnebel", forKey: "6;48")
        dict.updateValue("wolkig, Eisnebel", forKey: "6;49")
        dict.updateValue("wolkig, leichter Sprühregen", forKey: "6;50")
        dict.updateValue("wolkig, leichter Sprühregen", forKey: "6;51")
        dict.updateValue("wolkig, mäßiger Sprühregen", forKey: "6;52")
        dict.updateValue("wolkig, mäßiger Sprühregen", forKey: "6;53")
        dict.updateValue("wolkig, starker Sprühregen", forKey: "6;54")
        dict.updateValue("wolkig, starker Sprühregen", forKey: "6;55")
        dict.updateValue("wolkig, Sprühregen mit Glatteisgefahr", forKey: "6;56")
        dict.updateValue("wolkig, Sprühregen mit Glatteisgefahr", forKey: "6;57")
        dict.updateValue("wolkig, Sprühregen mit Regen", forKey: "6;58")
        dict.updateValue("wolkig, Sprühregen mit Regen", forKey: "6;59")
        dict.updateValue("wolkig, leichter Regen", forKey: "6;60")
        dict.updateValue("wolkig, leichter Regen", forKey: "6;61")
        dict.updateValue("wolkig, mäßiger Regen", forKey: "6;62")
        dict.updateValue("wolkig, mäßiger Regen", forKey: "6;63")
        dict.updateValue("wolkig, starker Regen", forKey: "6;64")
        dict.updateValue("wolkig, starker Regen", forKey: "6;65")
        dict.updateValue("wolkig, Regen mit Glatteisgefahr", forKey: "6;66")
        dict.updateValue("wolkig, Regen mit Glatteisgefahr", forKey: "6;67")
        dict.updateValue("wolkig, Schneeregen", forKey: "6;68")
        dict.updateValue("wolkig, Schneeregen", forKey: "6;69")
        dict.updateValue("wolkig, leichter Schneefall", forKey: "6;70")
        dict.updateValue("wolkig, leichter Schneefall", forKey: "6;71")
        dict.updateValue("wolkig, mäßiger Schneefall", forKey: "6;72")
        dict.updateValue("wolkig, mäßiger Schneefall", forKey: "6;73")
        dict.updateValue("wolkig, starker Schneefall", forKey: "6;74")
        dict.updateValue("wolkig, starker Schneefall", forKey: "6;75")
        dict.updateValue("wolkig, Eisnadeln", forKey: "6;76")
        dict.updateValue("wolkig, Schneegriesel", forKey: "6;77")
        dict.updateValue("wolkig, Eisnadeln", forKey: "6;78")
        dict.updateValue("wolkig, Eiskörner", forKey: "6;79")
        dict.updateValue("wolkig, Regenschauer", forKey: "6;80")
        dict.updateValue("wolkig, Regenschauer", forKey: "6;81")
        dict.updateValue("wolkig, Regenschauer", forKey: "6;82")
        dict.updateValue("wolkig, Schneeregenschauer", forKey: "6;83")
        dict.updateValue("wolkig, Schneeregenschauer", forKey: "6;84")
        dict.updateValue("wolkig, Schneeschauer", forKey: "6;85")
        dict.updateValue("wolkig, Schneeschauer", forKey: "6;86")
        dict.updateValue("wolkig, Graupelschauer", forKey: "6;87")
        dict.updateValue("wolkig, Graupelschauer", forKey: "6;88")
        dict.updateValue("wolkig, Hagelschauer", forKey: "6;89")
        dict.updateValue("wolkig, Hagelschauer", forKey: "6;90")
        dict.updateValue("wolkig, Gewitter", forKey: "6;91")
        dict.updateValue("wolkig, Gewitter", forKey: "6;92")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "6;93")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "6;94")
        dict.updateValue("wolkig, Gewitter", forKey: "6;95")
        dict.updateValue("wolkig, Graupelgewitter", forKey: "6;96")
        dict.updateValue("wolkig, Gewitter", forKey: "6;97")
        dict.updateValue("wolkig, Gewitter mit Staubsturm", forKey: "6;98")
        dict.updateValue("wolkig, starkes Graupelgewitter", forKey: "6;99")
        dict.updateValue("stark bewölkt, Schleierwolken", forKey: "7;-8")
        dict.updateValue("stark bewölkt, Schneesturm", forKey: "7;-7")
        dict.updateValue("stark bewölkt, Sturm", forKey: "7;-6")
        dict.updateValue("stark bewölkt, Glatteisgefahr", forKey: "7;-5")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;-4")
        dict.updateValue("stark bewölkt, Schneefall", forKey: "7;-3")
        dict.updateValue("stark bewölkt, Regenwolken", forKey: "7;-2")
        dict.updateValue("stark bewölkt, Regenwolken", forKey: "7;-1")
        dict.updateValue("stark bewölkt", forKey: "7;0")
        dict.updateValue("stark bewölkt", forKey: "7;1")
        dict.updateValue("stark bewölkt", forKey: "7;2")
        dict.updateValue("stark bewölkt", forKey: "7;3")
        dict.updateValue("stark bewölkt", forKey: "7;4")
        dict.updateValue("stark bewölkt", forKey: "7;5")
        dict.updateValue("stark bewölkt", forKey: "7;6")
        dict.updateValue("stark bewölkt", forKey: "7;7")
        dict.updateValue("stark bewölkt", forKey: "7;8")
        dict.updateValue("stark bewölkt", forKey: "7;9")
        dict.updateValue("stark bewölkt, Dunst", forKey: "7;10")
        dict.updateValue("stark bewölkt, Bodennebel", forKey: "7;11")
        dict.updateValue("stark bewölkt, Bodennebel", forKey: "7;12")
        dict.updateValue("stark bewölkt, Wetterleuchten", forKey: "7;13")
        dict.updateValue("stark bewölkt, Tropfen möglich", forKey: "7;14")
        dict.updateValue("stark bewölkt, etwas Regen", forKey: "7;15")
        dict.updateValue("stark bewölkt, etwas Regen", forKey: "7;16")
        dict.updateValue("stark bewölkt, gewittrig", forKey: "7;17")
        dict.updateValue("stark bewölkt, böig", forKey: "7;18")
        dict.updateValue("stark bewölkt, Tornado", forKey: "7;19")
        dict.updateValue("stark bewölkt, Sprühregen", forKey: "7;20")
        dict.updateValue("stark bewölkt, Regen", forKey: "7;21")
        dict.updateValue("stark bewölkt, Schneefall", forKey: "7;22")
        dict.updateValue("stark bewölkt, Schneeregen", forKey: "7;23")
        dict.updateValue("stark bewölkt, Schneeregen mit Glatteisgefahr", forKey: "7;24")
        dict.updateValue("stark bewölkt, Regenschauer", forKey: "7;25")
        dict.updateValue("stark bewölkt, Schneeschauer", forKey: "7;26")
        dict.updateValue("stark bewölkt, Graupelschauer", forKey: "7;27")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;28")
        dict.updateValue("stark bewölkt, gewittrig", forKey: "7;29")
        dict.updateValue("stark bewölkt, Staubsturm", forKey: "7;30")
        dict.updateValue("stark bewölkt, Staubsturm", forKey: "7;31")
        dict.updateValue("stark bewölkt, Staubsturm", forKey: "7;32")
        dict.updateValue("stark bewölkt, Staubsturm", forKey: "7;33")
        dict.updateValue("stark bewölkt, Staubsturm", forKey: "7;34")
        dict.updateValue("stark bewölkt, Staubsturm", forKey: "7;35")
        dict.updateValue("stark bewölkt, Schneefegen", forKey: "7;36")
        dict.updateValue("stark bewölkt, Schneefegen", forKey: "7;37")
        dict.updateValue("stark bewölkt, Schneetreiben", forKey: "7;38")
        dict.updateValue("stark bewölkt, Schneetreiben", forKey: "7;39")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;40")
        dict.updateValue("stark bewölkt, Nebeltreiben", forKey: "7;41")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;42")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;43")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;44")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;45")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;46")
        dict.updateValue("stark bewölkt, Nebel", forKey: "7;47")
        dict.updateValue("stark bewölkt, Eisnebel", forKey: "7;48")
        dict.updateValue("stark bewölkt, Eisnebel", forKey: "7;49")
        dict.updateValue("stark bewölkt, leichter Sprühregen", forKey: "7;50")
        dict.updateValue("stark bewölkt, leichter Sprühregen", forKey: "7;51")
        dict.updateValue("stark bewölkt, mäßiger Sprühregen", forKey: "7;52")
        dict.updateValue("stark bewölkt, mäßiger Sprühregen", forKey: "7;53")
        dict.updateValue("stark bewölkt, starker Sprühregen", forKey: "7;54")
        dict.updateValue("stark bewölkt, starker Sprühregen", forKey: "7;55")
        dict.updateValue("stark bewölkt, Sprühregen mit Glatteisgefahr", forKey: "7;56")
        dict.updateValue("stark bewölkt, Sprühregen mit Glatteisgefahr", forKey: "7;57")
        dict.updateValue("stark bewölkt, Sprühregen mit Regen", forKey: "7;58")
        dict.updateValue("stark bewölkt, Sprühregen mit Regen", forKey: "7;59")
        dict.updateValue("stark bewölkt, leichter Regen", forKey: "7;60")
        dict.updateValue("stark bewölkt, leichter Regen", forKey: "7;61")
        dict.updateValue("stark bewölkt, mäßiger Regen", forKey: "7;62")
        dict.updateValue("stark bewölkt, mäßiger Regen", forKey: "7;63")
        dict.updateValue("stark bewölkt, starker Regen", forKey: "7;64")
        dict.updateValue("stark bewölkt, starker Regen", forKey: "7;65")
        dict.updateValue("stark bewölkt, Regen mit Glatteisgefahr", forKey: "7;66")
        dict.updateValue("stark bewölkt, Regen mit Glatteisgefahr", forKey: "7;67")
        dict.updateValue("stark bewölkt, Schneeregen", forKey: "7;68")
        dict.updateValue("stark bewölkt, Schneeregen", forKey: "7;69")
        dict.updateValue("stark bewölkt, leichter Schneefall", forKey: "7;70")
        dict.updateValue("stark bewölkt, leichter Schneefall", forKey: "7;71")
        dict.updateValue("stark bewölkt, mäßiger Schneefall", forKey: "7;72")
        dict.updateValue("stark bewölkt, mäßiger Schneefall", forKey: "7;73")
        dict.updateValue("stark bewölkt, starker Schneefall", forKey: "7;74")
        dict.updateValue("stark bewölkt, starker Schneefall", forKey: "7;75")
        dict.updateValue("stark bewölkt, Eisnadeln", forKey: "7;76")
        dict.updateValue("stark bewölkt, Schneegriesel", forKey: "7;77")
        dict.updateValue("stark bewölkt, Eisnadeln", forKey: "7;78")
        dict.updateValue("stark bewölkt, Eiskörner", forKey: "7;79")
        dict.updateValue("stark bewölkt, Regenschauer", forKey: "7;80")
        dict.updateValue("stark bewölkt, Regenschauer", forKey: "7;81")
        dict.updateValue("stark bewölkt, Regenschauer", forKey: "7;82")
        dict.updateValue("stark bewölkt, Schneeregenschauer", forKey: "7;83")
        dict.updateValue("stark bewölkt, Schneeregenschauer", forKey: "7;84")
        dict.updateValue("stark bewölkt, Schneeschauer", forKey: "7;85")
        dict.updateValue("stark bewölkt, Schneeschauer", forKey: "7;86")
        dict.updateValue("stark bewölkt, Graupelschauer", forKey: "7;87")
        dict.updateValue("stark bewölkt, Graupelschauer", forKey: "7;88")
        dict.updateValue("stark bewölkt, Hagelschauer", forKey: "7;89")
        dict.updateValue("stark bewölkt, Hagelschauer", forKey: "7;90")
        dict.updateValue("stark bewölkt, Gewitter", forKey: "7;91")
        dict.updateValue("stark bewölkt, Gewitter", forKey: "7;92")
        dict.updateValue("stark bewölkt, Graupelgewitter", forKey: "7;93")
        dict.updateValue("stark bewölkt, Graupelgewitter", forKey: "7;94")
        dict.updateValue("stark bewölkt, Gewitter", forKey: "7;95")
        dict.updateValue("stark bewölkt, Graupelgewitter", forKey: "7;96")
        dict.updateValue("stark bewölkt, Gewitter", forKey: "7;97")
        dict.updateValue("stark bewölkt, Gewitter mit Staubsturm", forKey: "7;98")
        dict.updateValue("stark bewölkt, starkes Graupelgewitter", forKey: "7;99")
        dict.updateValue("bedeckt, Schleierwolken", forKey: "8;-8")
        dict.updateValue("bedeckt, Schneesturm", forKey: "8;-7")
        dict.updateValue("bedeckt, Sturm", forKey: "8;-6")
        dict.updateValue("bedeckt, Glatteisgefahr", forKey: "8;-5")
        dict.updateValue("bedeckt, Nebel", forKey: "8;-4")
        dict.updateValue("bedeckt, Schneefall", forKey: "8;-3")
        dict.updateValue("bedeckt, Regenwolken", forKey: "8;-2")
        dict.updateValue("bedeckt, Regenwolken", forKey: "8;-1")
        dict.updateValue("bedeckt", forKey: "8;0")
        dict.updateValue("bedeckt", forKey: "8;1")
        dict.updateValue("bedeckt", forKey: "8;2")
        dict.updateValue("bedeckt", forKey: "8;3")
        dict.updateValue("bedeckt", forKey: "8;4")
        dict.updateValue("bedeckt", forKey: "8;5")
        dict.updateValue("bedeckt", forKey: "8;6")
        dict.updateValue("bedeckt", forKey: "8;7")
        dict.updateValue("bedeckt", forKey: "8;8")
        dict.updateValue("bedeckt", forKey: "8;9")
        dict.updateValue("bedeckt, Dunst", forKey: "8;10")
        dict.updateValue("bedeckt, Bodennebel", forKey: "8;11")
        dict.updateValue("bedeckt, Bodennebel", forKey: "8;12")
        dict.updateValue("bedeckt, Wetterleuchten", forKey: "8;13")
        dict.updateValue("bedeckt, Tropfen möglich", forKey: "8;14")
        dict.updateValue("bedeckt, etwas Regen", forKey: "8;15")
        dict.updateValue("bedeckt, etwas Regen", forKey: "8;16")
        dict.updateValue("bedeckt, gewittrig", forKey: "8;17")
        dict.updateValue("bedeckt, böig", forKey: "8;18")
        dict.updateValue("bedeckt, Tornado", forKey: "8;19")
        dict.updateValue("bedeckt, Sprühregen", forKey: "8;20")
        dict.updateValue("bedeckt, Regen", forKey: "8;21")
        dict.updateValue("bedeckt, Schneefall", forKey: "8;22")
        dict.updateValue("bedeckt, Schneeregen", forKey: "8;23")
        dict.updateValue("bedeckt, Schneeregen mit Glatteisgefahr", forKey: "8;24")
        dict.updateValue("bedeckt, Regenschauer", forKey: "8;25")
        dict.updateValue("bedeckt, Schneeschauer", forKey: "8;26")
        dict.updateValue("bedeckt, Graupelschauer", forKey: "8;27")
        dict.updateValue("bedeckt, Nebel", forKey: "8;28")
        dict.updateValue("bedeckt, gewittrig", forKey: "8;29")
        dict.updateValue("bedeckt, Staubsturm", forKey: "8;30")
        dict.updateValue("bedeckt, Staubsturm", forKey: "8;31")
        dict.updateValue("bedeckt, Staubsturm", forKey: "8;32")
        dict.updateValue("bedeckt, Staubsturm", forKey: "8;33")
        dict.updateValue("bedeckt, Staubsturm", forKey: "8;34")
        dict.updateValue("bedeckt, Staubsturm", forKey: "8;35")
        dict.updateValue("bedeckt, Schneefegen", forKey: "8;36")
        dict.updateValue("bedeckt, Schneefegen", forKey: "8;37")
        dict.updateValue("bedeckt, Schneetreiben", forKey: "8;38")
        dict.updateValue("bedeckt, Schneetreiben", forKey: "8;39")
        dict.updateValue("bedeckt, Nebel", forKey: "8;40")
        dict.updateValue("bedeckt, Nebeltreiben", forKey: "8;41")
        dict.updateValue("bedeckt, Nebel", forKey: "8;42")
        dict.updateValue("bedeckt, Nebel", forKey: "8;43")
        dict.updateValue("bedeckt, Nebel", forKey: "8;44")
        dict.updateValue("bedeckt, Nebel", forKey: "8;45")
        dict.updateValue("bedeckt, Nebel", forKey: "8;46")
        dict.updateValue("bedeckt, Nebel", forKey: "8;47")
        dict.updateValue("bedeckt, Eisnebel", forKey: "8;48")
        dict.updateValue("bedeckt, Eisnebel", forKey: "8;49")
        dict.updateValue("bedeckt, leichter Sprühregen", forKey: "8;50")
        dict.updateValue("bedeckt, leichter Sprühregen", forKey: "8;51")
        dict.updateValue("bedeckt, mäßiger Sprühregen", forKey: "8;52")
        dict.updateValue("bedeckt, mäßiger Sprühregen", forKey: "8;53")
        dict.updateValue("bedeckt, starker Sprühregen", forKey: "8;54")
        dict.updateValue("bedeckt, starker Sprühregen", forKey: "8;55")
        dict.updateValue("bedeckt, Sprühregen mit Glatteisgefahr", forKey: "8;56")
        dict.updateValue("bedeckt, Sprühregen mit Glatteisgefahr", forKey: "8;57")
        dict.updateValue("bedeckt, Sprühregen mit Regen", forKey: "8;58")
        dict.updateValue("bedeckt, Sprühregen mit Regen", forKey: "8;59")
        dict.updateValue("bedeckt, leichter Regen", forKey: "8;60")
        dict.updateValue("bedeckt, leichter Regen", forKey: "8;61")
        dict.updateValue("bedeckt, mäßiger Regen", forKey: "8;62")
        dict.updateValue("bedeckt, mäßiger Regen", forKey: "8;63")
        dict.updateValue("bedeckt, starker Regen", forKey: "8;64")
        dict.updateValue("bedeckt, starker Regen", forKey: "8;65")
        dict.updateValue("bedeckt, Regen mit Glatteisgefahr", forKey: "8;66")
        dict.updateValue("bedeckt, Regen mit Glatteisgefahr", forKey: "8;67")
        dict.updateValue("bedeckt, Schneeregen", forKey: "8;68")
        dict.updateValue("bedeckt, Schneeregen", forKey: "8;69")
        dict.updateValue("bedeckt, leichter Schneefall", forKey: "8;70")
        dict.updateValue("bedeckt, leichter Schneefall", forKey: "8;71")
        dict.updateValue("bedeckt, mäßiger Schneefall", forKey: "8;72")
        dict.updateValue("bedeckt, mäßiger Schneefall", forKey: "8;73")
        dict.updateValue("bedeckt, starker Schneefall", forKey: "8;74")
        dict.updateValue("bedeckt, starker Schneefall", forKey: "8;75")
        dict.updateValue("bedeckt, Eisnadeln", forKey: "8;76")
        dict.updateValue("bedeckt, Schneegriesel", forKey: "8;77")
        dict.updateValue("bedeckt, Eisnadeln", forKey: "8;78")
        dict.updateValue("bedeckt, Eiskörner", forKey: "8;79")
        dict.updateValue("bedeckt, Regenschauer", forKey: "8;80")
        dict.updateValue("bedeckt, Regenschauer", forKey: "8;81")
        dict.updateValue("bedeckt, Regenschauer", forKey: "8;82")
        dict.updateValue("bedeckt, Schneeregenschauer", forKey: "8;83")
        dict.updateValue("bedeckt, Schneeregenschauer", forKey: "8;84")
        dict.updateValue("bedeckt, Schneeschauer", forKey: "8;85")
        dict.updateValue("bedeckt, Schneeschauer", forKey: "8;86")
        dict.updateValue("bedeckt, Graupelschauer", forKey: "8;87")
        dict.updateValue("bedeckt, Graupelschauer", forKey: "8;88")
        dict.updateValue("bedeckt, Hagelschauer", forKey: "8;89")
        dict.updateValue("bedeckt, Hagelschauer", forKey: "8;90")
        dict.updateValue("bedeckt, Gewitter", forKey: "8;91")
        dict.updateValue("bedeckt, Gewitter", forKey: "8;92")
        dict.updateValue("bedeckt, Graupelgewitter", forKey: "8;93")
        dict.updateValue("bedeckt, Graupelgewitter", forKey: "8;94")
        dict.updateValue("bedeckt, Gewitter", forKey: "8;95")
        dict.updateValue("bedeckt, Graupelgewitter", forKey: "8;96")
        dict.updateValue("bedeckt, Gewitter", forKey: "8;97")
        dict.updateValue("bedeckt, Gewitter mit Staubsturm", forKey: "8;98")
        dict.updateValue("bedeckt, starkes Graupelgewitter", forKey: "8;99")

        self.dict = dict
        //DEBUG
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
        
        let nf = NumberFormatter()
        nf.numberStyle = NumberFormatter.Style.decimal
        nf.maximumFractionDigits = 0
        
            for node in doc.xpath("//day") {
                
                

                if
                let datum = dateFormatter.date(from: node["dtg"] ?? "" )?.string(),
                let tiefsttemperatur = nf.string(for: (Double(node["tn"] ?? "0")?.rounded())),
                let höchsttemperatur = nf.string(for: (Double(node["tx_n"] ?? "0")?.rounded())),
                let sonnenscheindauer = node["sun"],
                let regenwahrscheinlichkeit = node["prrr"],
                let symbol = node["symbol"],
                let n = node["n"],
                let ww = node["ww"],
                let dictn = dict[n],
                let dictww = dict[ww]
                {
                    let wettercode = dictn  + ";" + dictww
                    alleTageswetter.append(Tageswetter(datum: datum, tiefsttemperatur: tiefsttemperatur, höchsttemperatur: höchsttemperatur, sonnenscheindauer: sonnenscheindauer, regenwahrscheinlichkeit: regenwahrscheinlichkeit, wettercode: wettercode, symbol: symbol))
                }
                

        }

    }
 
   
    
}

extension Date {
    func string() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "EEEE, d. MMM"
        return formatter.string(from: self)
    }
}
