version: '3.2'

services:
  web:
    build: .
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      PORT: 4000
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      HOST: "wetter.krystof.eu"
    ports:
      - "4004:4000"
    command: foreground
