version: '2'
services:
  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  web:
    build: .
    environment:
      - MIX_ENV=prod
    command: sh -c "mix ecto.migrate && mix phx.server"
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/wetter"
      PORT: 4000
      POOL_SIZE: 10
    ports:
      - "4004:4000"
    depends_on:
      - db