# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: blackboxms/ubuntu-nodejs-elixir:1.9.2

    environment:
      MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-build

      # Test
      - run: mix deps.get
      - run: mix test

      # Build
      - run: cd ~/repo && git reset --hard && git clean -dfx
      - run: echo "$VAULT_PASS" | base64 -d > ~/repo/.ansible/.vault_pass.txt
      - run: cd .ansible && ansible-playbook -i apps/build/inventory-ci --extra-vars "app_name=wetter git_repo=git@github.com:krystofbe/wetter.git" apps/build/build.yml -vvv

      - save_cache:
          key: deps-build
          paths:
            - ~/repo/_build
            - ~/repo/deps
      # Install rsync for deploy
      - run: apt-get install rsync -y
      - deploy:
          name: "Deploy master to production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd .ansible && ansible-playbook -i apps/production/inventory-ci --extra-vars "app_name=wetter git_repo=git@github.com:krystofbe/wetter.git" apps/production/deploy.yml -vvv;
            fi
